tweetList = [
	"Two in the hand is worth one in the bush",
	"A watched pot never boils",
	"Destroy the seed of evil, or it will grow up to your ruin.",
	"A small fire is soon quenched.",
	"The Changjiang River waves behind drive the waves ahead.",
	"Trial often exhibits truly wonderful results.",
	"When baffled in one direction a man of energy will not despair, but will find another way to his object.",
	"A good opportunity is seldom presented, and is easily lost.",
	"Father's debt, son to give back."
	"Do not harbour intentions to hurt others.",
	"We all have a mental list of 'I should have's'.",
	"The one who makes trouble can resolve the trouble.",
	"Consuming alcohol assists with removing deceit and revealing the truth."
	"Nothing in life is to be feared, it is only to be understood.",
	"It is supposed that if there is a rumour, there must be some truth behind it.",
	"Present afflictions may tend to our future good.",
	"Every person bears resemblance to the ones who brought them into this world.",
	"Plans are insulted destinies. I don't have plans, I only have goals.",
	"Three monks have no water to drink.",
	"Try to save the dead horse as if it is still alive.",
	"Do the impossible, for it may truly be possible.",
	"Teachers open the door. You enter by yourself.",
	"You can lead the horse to the water, but you can't make it drink.",
	"Teach a man to take a fish is not equal to teach a man how to fish.",
	"When the tree falls, the monkeys scatter.",
	"Rats desert a sinking ship.",
	"Not only can water float a boat, it can sink it also.",
	"Measure thrice, cut once.",
	"The sky is big and the emperor is far away.",
	"One bitten by a snake for a snap dreads a rope for a decade.",
	"Sow thin, reap thin.",
	"A book is like a garden carried in the pocket.",
	"Those who scratch bottoms should not bite fingernails.",
	]
